---
title: "Extract CIC list location level"
author: "Meng Ye"
date: "2024-06-13"
output: html_document
---

### Load packages 

```{r load package, message=FALSE, warning=FALSE}
library(tidyverse) # package for data cleaning and plotting
library(here) # manage directory
library(readxl) # read excel file

set.seed(5432)
```


### Import Raw Data 


```{r import data 0, message=FALSE, warning=FALSE}
# import location level full data
locations<- read_excel(here("data","2019_oct_ratings.xlsx"), sheet = 2)
```



```{r}
cic <- locations %>% 
  rename(provider_name = `Provider Name`,
         location_name = `Location Name`) 
```


```{r sample std}
cic_renamed <- cic %>% 
# remove dots
  mutate(std_name = str_replace_all(provider_name, "\\.", "")) %>% 
# capitalize all
  mutate(std_name = str_to_upper(std_name)) %>%
# standardize to LTD
  mutate(std_name = str_replace_all(std_name, "LIMITED", "LTD")) %>% 
# standardize to CIC
  mutate(std_name = str_replace_all(std_name, "COMMUNITY INTEREST COMPANY", "CIC"))
```


```{r}
cic_location_list <- cic_renamed %>% 
filter(str_detect(std_name, "CIC")) %>%
  group_by(location_name) %>%
  slice(1)
```


```{r}
cic_provider_list <- cic_renamed %>%
  filter(str_detect(std_name, "CIC")) %>%
  group_by(provider_name) %>%
  slice(1)
```



```{r}
write_csv(cic_provider_list, file = here("cleaned_data", "cic2019_provider.csv"))
write_csv(cic_location_list, file = here("cleaned_data", "cic2019_location.csv"))
```



